openapi: 3.0.3
info:
  description: 'Quản lý API dự án framework 2'
  version: '1.0.0'
  title: 'Swagger Quản lý dự án framework 2'
  contact:
    email: 'hungdang02042003@gmail.com'
  license:
    name: 'Nginx'
tags:
  - name: Order
    description: API quản lý đơn hàng
paths:
  /create-order:
    post:
      tags:
        - Order
      summary: Tạo đơn hàng mới
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '200':
          description: Đơn hàng được tạo thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          description: Lỗi trong quá trình tạo đơn hàng

  /orders:
    get:
      tags:
        - Order
      summary: Lấy tất cả các đơn hàng
      parameters:
        - in: query
          name: _page
          schema:
            type: integer
          description: Trang số (mặc định là 1)
        - in: query
          name: _limit
          schema:
            type: integer
          description: Số lượng đơn hàng trên mỗi trang (mặc định là 10)
        - in: query
          name: q
          schema:
            type: string
          description: Từ khóa tìm kiếm đơn hàng
      responses:
        '200':
          description: Danh sách các đơn hàng
          content:
            application/json:
              schema:
                type: object
                properties:
                  docs:
                    type: array
                    items:
                      $ref: '#/components/schemas/Order'
                  totalDocs:
                    type: integer
                  limit:
                    type: integer
                  page:
                    type: integer
                  totalPages:
                    type: integer
        '400':
          description: Lỗi trong quá trình lấy đơn hàng

  /order/{id}:
    get:
      tags:
        - Order
      summary: Lấy thông tin một đơn hàng theo ID
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Mã đơn hàng
      responses:
        '200':
          description: Thông tin chi tiết của đơn hàng
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          description: Lỗi trong quá trình lấy thông tin đơn hàng
    delete:
      tags:
        - Order
      summary: Xóa đơn hàng
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Mã đơn hàng
      responses:
        '200':
          description: Đơn hàng đã được xóa thành công
        '400':
          description: Lỗi trong quá trình xóa đơn hàng
  /order/confirmed/{id}:
    put:
      tags:
        - Order
      summary: Cập nhật trạng thái đơn hàng thành confirmed
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Mã đơn hàng
      responses:
        '200':
          description: Đơn hàng đã được cập nhật thành confirmed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          description: Lỗi trong quá trình cập nhật trạng thái đơn hàng

  /order/delivered/{id}:
    put:
      tags:
        - Order
      summary: Cập nhật trạng thái đơn hàng thành delivered
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Mã đơn hàng
      responses:
        '200':
          description: Đơn hàng đã được cập nhật thành delivered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          description: Lỗi trong quá trình cập nhật trạng thái đơn hàng

  /order/done/{id}:
    put:
      tags:
        - Order
      summary: Cập nhật trạng thái đơn hàng thành done
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Mã đơn hàng
      responses:
        '200':
          description: Đơn hàng đã được cập nhật thành done
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          description: Lỗi trong quá trình cập nhật trạng thái đơn hàng

  /order/canceled/{id}:
    put:
      tags:
        - Order
      summary: Cập nhật trạng thái đơn hàng thành canceled
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Mã đơn hàng
      responses:
        '200':
          description: Đơn hàng đã được cập nhật thành canceled
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          description: Lỗi trong quá trình cập nhật trạng thái đơn hàng

  /order/pending/{id}:
    put:
      tags:
        - Order
      summary: Cập nhật trạng thái đơn hàng thành pending
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Mã đơn hàng
      responses:
        '200':
          description: Đơn hàng đã được cập nhật thành pending
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          description: Lỗi trong quá trình cập nhật trạng thái đơn hàng

  /order-confirmed:
    get:
      tags:
        - Order
      summary: Lấy tất cả các đơn hàng đã được xác nhận
      parameters:
        - in: query
          name: _page
          schema:
            type: integer
          description: Trang số (mặc định là 1)
        - in: query
          name: _limit
          schema:
            type: integer
          description: Số lượng đơn hàng trên mỗi trang (mặc định là 10)
        - in: query
          name: q
          schema:
            type: string
          description: Từ khóa tìm kiếm đơn hàng
      responses:
        '200':
          description: Danh sách các đơn hàng đã được xác nhận
          content:
            application/json:
              schema:
                type: object
                properties:
                  docs:
                    type: array
                    items:
                      $ref: '#/components/schemas/Order'
                  totalDocs:
                    type: integer
                  limit:
                    type: integer
                  page:
                    type: integer
                  totalPages:
                    type: integer
        '400':
          description: Lỗi trong quá trình lấy đơn hàng đã được xác nhận

  /order-delivered:
    get:
      tags:
        - Order
      summary: Lấy tất cả các đơn hàng đã được giao hàng
      parameters:
        - in: query
          name: _page
          schema:
            type: integer
          description: Trang số (mặc định là 1)
        - in: query
          name: _limit
          schema:
            type: integer
          description: Số lượng đơn hàng trên mỗi trang (mặc định là 10)
        - in: query
          name: q
          schema:
            type: string
          description: Từ khóa tìm kiếm đơn hàng
      responses:
        '200':
          description: Danh sách các đơn hàng đã được giao hàng
          content:
            application/json:
              schema:
                type: object
                properties:
                  docs:
                    type: array
                    items:
                      $ref: '#/components/schemas/Order'
                  totalDocs:
                    type: integer
                  limit:
                    type: integer
                  page:
                    type: integer
                  totalPages:
                    type: integer
        '400':
          description: Lỗi trong quá trình lấy đơn hàng đã được giao hàng

  /order-done:
    get:
      tags:
        - Order
      summary: Lấy tất cả các đơn hàng đã hoàn thành
      parameters:
        - in: query
          name: _page
          schema:
            type: integer
          description: Trang số (mặc định là 1)
        - in: query
          name: _limit
          schema:
            type: integer
          description: Số lượng đơn hàng trên mỗi trang (mặc định là 10)
        - in: query
          name: q
          schema:
            type: string
          description: Từ khóa tìm kiếm đơn hàng
      responses:
        '200':
          description: Danh sách các đơn hàng đã hoàn thành
          content:
            application/json:
              schema:
                type: object
                properties:
                  docs:
                    type: array
                    items:
                      $ref: '#/components/schemas/Order'
                  totalDocs:
                    type: integer
                  limit:
                    type: integer
                  page:
                    type: integer
                  totalPages:
                    type: integer
        '400':
          description: Lỗi trong quá trình lấy đơn hàng đã hoàn thành

  /order-canceled:
    get:
      tags:
        - Order
      summary: Lấy tất cả các đơn hàng đã bị hủy
      parameters:
        - in: query
          name: _page
          schema:
            type: integer
          description: Trang số (mặc định là 1)
        - in: query
          name: _limit
          schema:
            type: integer
          description: Số lượng đơn hàng trên mỗi trang (mặc định là 10)
        - in: query
          name: q
          schema:
            type: string
          description: Từ khóa tìm kiếm đơn hàng
      responses:
        '200':
          description: Danh sách các đơn hàng đã bị hủy
          content:
            application/json:
              schema:
                type: object
                properties:
                  docs:
                    type: array
                    items:
                      $ref: '#/components/schemas/Order'
                  totalDocs:
                    type: integer
                  limit:
                    type: integer
                  page:
                    type: integer
                  totalPages:
                    type: integer
        '400':
          description: Lỗi trong quá trình lấy đơn hàng đã bị hủy

  /order-pending:
    get:
      tags:
        - Order
      summary: Lấy tất cả các đơn hàng đang chờ xử lý
      parameters:
        - in: query
          name: _page
          schema:
            type: integer
          description: Trang số (mặc định là 1)
        - in: query
          name: _limit
          schema:
            type: integer
          description: Số lượng đơn hàng trên mỗi trang (mặc định là 10)
        - in: query
          name: q
          schema:
            type: string
          description: Từ khóa tìm kiếm đơn hàng
      responses:
        '200':
          description: Danh sách các đơn hàng đang chờ xử lý
          content:
            application/json:
              schema:
                type: object
                properties:
                  docs:
                    type: array
                    items:
                      $ref: '#/components/schemas/Order'
                  totalDocs:
                    type: integer
                  limit:
                    type: integer
                  page:
                    type: integer
                  totalPages:
                    type: integer
        '400':
          description: Lỗi trong quá trình lấy đơn hàng đang chờ xử lý


components:
  schemas:
    Order:
      type: object
      properties:
        _id:
          type: string
          description: Mã đơn hàng
        user:
          type: string
          description: Mã người dùng
        items:
          type: array
          items:
            type: object
            properties:
              product:
                type: string
                description: Mã sản phẩm
              quantity:
                type: number
                description: Số lượng sản phẩm
              price:
                type: number
                description: Giá sản phẩm
          description: Các mục hàng trong đơn hàng
        status:
          type: string
          enum: [pending, confirmed, delivered, done, canceled]
          description: Trạng thái đơn hàng
        total:
          type: number
          description: Tổng giá trị đơn hàng
        priceShipping:
          type: number
          description: Phí vận chuyển
        address:
          type: string
          description: Địa chỉ giao hàng
        is_active:
          type: boolean
          description: Trạng thái hoạt động của đơn hàng
      required:
        - user
        - items
        - status
        - address
      example:
        _id: 1234567890
        user: 0987654321
        items:
          - product: 9876543210
            quantity: 2
            price: 10
        status: pending
        total: 20
        priceShipping: 5
        address: 123 Main St
        is_active: true
